# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 898d9318867e9dff0c69f482334b35faaa480214d23d7de4f079bafb43cb15cb5087d10d447a18c469a45a8e4a80b2c9a4eba46603f751e4a7dc9287b33c4abb

test:
  secret_key_base: 4ff554a2ee03c842c8c736dbf4f62c85a5a5c19fc8c1ca9f13e4b47030f1ca1ca308f98ea02a15d0eccaecde801256dd97d9c4c6974438642a0752159a6dbd7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
